### ISSUE TITLE
max_actors fail

### ISSUE THREAD

**Issue by jimlynnjulian** [preritdas/rottentomatoes-python#12]
Just tried the program. Thanks, RT access is not easy in batch mode.
I ran the first example in the readme, and the following error occurred:
"Traceback (most recent call last):
  File "C:\Users\jimly\Desktop\IMDB dataset SQLite\other movie databases\rottentomatoes-python\rtp-script00.py", line 27, in <module>
    print(rt.actors('top gun maverick', max_actors=5))
TypeError: actors() got an unexpected keyword argument 'max_actors' "

offending 'line 27': "print(rt.actors('top gun maverick', max_actors=5))"

I'm running python3 on Windows 11 Pro, CLI (MS-DOS).

**Comment by preritdas** [comment]
Thanks. Please bump to version 0.5.18 for `max_actors` support in the `stadalone.actors` function. This flag was disabled earlier after some site migrations but remained in the examples. It's now reimplemented and passing in tests. Please re-open this issue if it doesn't seem to be working properly in 0.5.18!

**Comment by jimlynnjulian** [comment]
Thanks. Worked. I had to uninstall 0.5.17 first, though.
