### ISSUE TITLE
Site structure fix needed

### ISSUE THREAD

**Issue by preritdas** [preritdas/rottentomatoes-python#35]
Content fed into `_get_score_details()` does not contain the starting string as it used to.

**Comment by SuperrMurlocc** [comment]
For a quick fix for my project I managed to get it working by changing the function `_get_score_details()` into:

```python
return json.loads(
        _extract(
            content,
            '<script id="media-scorecard-json" data-json="mediaScorecard" type="application/json">',
            '</script>'
        )
    )
```

This way it does return a proper JSON object but the keys are different, inside `tomatometer` I had to change to:

```python
scoreboard = _get_score_details(content)['criticsScore']

    if "score" not in scoreboard:
        return None

    return scoreboard["score"]
```

and inside `audience_score` to:

```python
scoreboard = _get_score_details(content)['audienceScore']

    if "score" not in scoreboard:
        return None
    
    return scoreboard["score"]
```

I don't use other fields but if you'd like for functions like `rating`, `duration` and `year_released` to be working you need to create a function for getting other JSON object, this info is now stored in:

```html
<script id="media-hero-json" data-json="mediaHero" type="application/json">
   ...
</script>
```

**Comment by ajkessel** [comment]
Is there a full fix that could be turned into a pull request?

**Comment by SuperrMurlocc** [comment]
I'm afraid not, recently i encountered varieties concerning movies' release year. Sometimes it is near:
```html
<rt-text class="key" size="0.875">Release Date (Theaters)</rt-text>
```
and sometimes near:
```html
<rt-text size="0.75" style="--textColor: var(--white)" slot="releaseDate">
```

My function currently looks like so:

```py
def year_released(movie_name: str, content: str = None) -> str:
    """Returns a string of the year the movie was released."""
    if content is None:
        content = _request(movie_name)

    if '<rt-text class="key" size="0.875">Release Date (Theaters)</rt-text>' in content:

        idx = content.find('<rt-text class="key" size="0.875">Release Date (Theaters)</rt-text>')
        c = _extract(
            _extract(
                content[idx - 300: idx + 300],
                '<div class="category-wrap">',
                '</div>'
            ),
            '<rt-text>',
            '</rt-text>'
        )

        r = re.findall("\\d{4}", c)
        year = int(r[0])

    else:
        year = int(_extract(
                content,
                '<rt-text size="0.75" style="--textColor: var(--white)" slot="releaseDate">',
                '</rt-text>'
            ),)

    return year
```

it works but is a mess that is not pr-worthy. I guess that rotten-tomatoes changed the way they display the data on their website and hence the problems with this package.

This and potentially other problems make it not possible for me to submit a pull request.

**Comment by preritdas** [comment]
Fixed thanks to @GarrisonBates.
