### ISSUE TITLE
Request to add the URL to the underlying page to the object model

### ISSUE THREAD

**Issue by ajkessel** [preritdas/rottentomatoes-python#36]
It would be handy if the object could include a URL to the page from which data originated. I don't see this anywhere in the current code but presumably would not be hard to add -- is this possible?

**Comment by ajkessel** [comment]
It seems like this is already in there, it just needs to be better exposed, e.g.:
```
url = rt.search.top_movie_result(name).url
```

**Comment by preritdas** [comment]
I like that idea. Would be great if you could open a PR, if the implementation is straightforward, otherwise I'll try to get to it when I can later.

**Comment by ajkessel** [comment]
Actually, this is easier than I thought. The functionality is already there:
```
rt.url(name)
```
Works. It just needs to be added to the documentation.

**Comment by ajkessel** [comment]
Suggested fix in #44
