### ISSUE TITLE
Lookups not working - Internal Server Error

### ISSUE THREAD

**Issue by bengt-a** [preritdas/rottentomatoes-python#37]
When I try to use the tool, any lookup renders "Internal Server Error"

Example:
https://rotten-tomatoes-api.ue.r.appspot.com/movie/dune

**Comment by preritdas** [comment]
This is because of #35. Might you be able to contribute a fix?

**Comment by bengt-a** [comment]
Thanks for the trust. Alas, I would not know how to fix it.

I found another tool for fetching RT-scores

**Comment by SanketBaraiya** [comment]
Hi Team, Any updates on this?

Also @bengt-a can you please specify the tool which you found and is it open-source or paid?

Thanks

**Comment by preritdas** [comment]
Fixed thanks to @GarrisonBates.

**Comment by bengt-a** [comment]
> Hi Team, Any updates on this?
> 
> Also @bengt-a can you please specify the tool which you found and is it open-source or paid?
> 
> Thanks

Hi,
I found https://omdbapi.com where you can fetch a bunch of metadata for movies. It's great!
